version: 2

requirements:
  signed_off_by:
    required: false

group_defaults:
  required: 2
  approve_by_comment:
    enabled: true
    approve_regex: ^LGTM
    reject_regex: ^Rejected
  reset_on_push:
    enabled: true
  author_approval:
    ignored: true
  always_pending:
    title_regex: ^WIP
    explanation: 'Work in progress...'
  conditions:
    branches:
      - master

groups:
  runtime-spec:
    teams:
      - runtime-spec-maintainers
