language: go
go:
  - 1.4.2
  - 1.3.3

sudo: false

before_install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get gopkg.in/yaml.v2

install: true

script:
  - echo ${TRAVIS_COMMIT_RANGE}
  - go run .tools/validate.go -range ${TRAVIS_COMMIT_RANGE}
  
